# Generated by Django 3.0.2 on 2020-01-20 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cw22', '0003_diary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='diary',
        ),
        migrations.AddField(
            model_name='diary',
            name='students',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='cw22.Student'),
        ),
    ]
