# Generated by Django 3.0.2 on 2020-01-20 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cw22', '0004_auto_20200120_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='students',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary', to='cw22.Student'),
        ),
    ]
