# Generated by Django 3.0.2 on 2020-01-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cw22', '0005_auto_20200120_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='students',
            new_name='student',
        ),
    ]
