# Generated by Django 3.0.2 on 2020-01-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw22', '0006_auto_20200120_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('students', models.ManyToManyField(null=True, related_name='books', to='cw22.Student')),
            ],
        ),
    ]
