# Generated by Django 3.0.2 on 2020-01-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw22', '0007_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='students',
            field=models.ManyToManyField(related_name='books', to='cw22.Student'),
        ),
    ]
