# Generated by Django 3.0.2 on 2020-01-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw23', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='release_date',
        ),
        migrations.AddField(
            model_name='car',
            name='release_year',
            field=models.IntegerField(null=True),
        ),
    ]
