# Generated by Django 3.0.2 on 2020-01-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=20)),
                ('created', models.DateField(auto_now_add=True)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
